name: Get IAP Token

author: fcoclavero

description: |-
  GitHub action for setting up a Cloud SQL Proxy that can be used by later steps.

inputs:
  credentials: # input id
    description: "The service account key to use for authentication. It should be stored as a secret."
    required: false

  instance_connection_name: # input id
    description: "The DB's instance connection name. It can be retrieved from the DB's details in the Cloud SQL console"
    required: true

  port: # input id
    description: "The IP where the port will be exposed in the localhost."
    default: "5432" # postgres default
    required: true

runs:
  using: node12
  main: dist/index.js
