name: Get IAP Token
author: fcoclavero
description: |-
  Get a JWT that can be used to authenticate API calls behind a Goocle Cloud
  Identity Aware Proxy (IAP).
inputs:
  iap-oauth-client-id: # id of input
    description: "Client ID for the IAP OAuth client."
    required: true
  credentials: # id of input
    description: "The service account key which will be used for authentication. This key should be created, encoded as a Base64 string (eg. cat my-key.json | base64 on macOS), and stored as a secret."
    required: true
  service-account: # id of input
    description: "Service account email address."
    required: true
  token-duration: # id of input
    description: "Token duration in seconds. Tokens must be short lived (1 hour tops)."
    required: false
    default: "3600"
outputs:
  token: # id of output
    description: The IAP authentication JWT.
runs:
  using: node12
  main: dist/index.js
