name: Get IAP Token

author: fcoclavero

description: |-
  Get a JWT that can be used to authenticate API calls behind a Goocle Cloud
  Identity Aware Proxy (IAP).

inputs:
  iap_oauth_client_id: # input id
    description: "The client ID for the IAP OAuth client."
    required: true

  service_account_key: # input id
    description: "The service account key to use for authentication. It should be stored as a secret."
    required: false

outputs:
  token: # id of output
    description: The IAP authentication JWT.

runs:
  using: node12
  main: dist/index.js
