name: cloud-sql-proxy Integration

on:
  push:
    paths:
      - "cloud-sql-proxy/**"
      - ".github/workflows/cloud-sql-proxy*"

jobs:
  connect-via-proxy:
    name: Authenticate with setup-gcloud.
    runs-on: ubuntu-latest
    services:
      cloud-sql-proxy: # label used to access the service container
        image: fcoclavero/docker-cloudsqlproxy:latest # Docker Hub image
        ports: # Opens tcp ports on the host and service container
          - 5432:5432
        env:
          CLOUDSQL_CREDENTIALS: ${{ secrets.SA_KEY }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          CLOUDSQL_ZONE: ${{ secrets.INSTANCE_ZONE }}
          CLOUDSQL_INSTANCE: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          PORT: 5432
    steps:
      - uses: actions/checkout@v2
        run: psql "host=127.0.0.1 port=5432 sslmode=disable dbname=${{ secrets.DB_NAME }} user=${{ secrets.DB_USER_NAME }} password=${{ secrets.DB_PASSWORD }}"
<<<<<<< HEAD
=======
        continue-on-error: true
>>>>>>> 25f7aa0... Cleanup
