name: cloud-sql-proxy Integration

on:
  push:
    paths:
      - "cloud-sql-proxy/**"
      - ".github/workflows/cloud-sql-proxy*"

jobs:
  gcloud:
    name: Authenticate with setup-gcloud.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-gcloud
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_B64 }}
      - id: cloud-sql-proxy
        name: setup Cloud SQL proxy
        uses: ./cloud-sql-proxy
        with:
          instance_connection_name: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          port: ${{ secrets.CLOUD_SQL_PROXY_PORT }}

  json:
    name: Authenticate with JSON credentials.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cloud-sql-proxy
        name: setup Cloud SQL proxy
        uses: ./cloud-sql-proxy
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          instance_connection_name: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          port: ${{ secrets.CLOUD_SQL_PROXY_PORT }}
