name: get-iap-token Integration

on:
  push:
    paths:
      - "get-iap-token/**"
      - ".github/workflows/get-iap-token*"

jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-gcloud
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_B64 }}
          export_default_credentials: true
      - id: iap-token
        name: get IAP token
        uses: ./get-iap-token
        with:
          iap-oauth-client-id: ${{ secrets.IAP_OAUTH_CLIENT_ID }}
          service-account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: get output
        run: echo '${{ steps.iap-token.outputs.token }}'

  b64_json:
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: iap-token
        name: get IAP token
        uses: ./get-iap-token
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_B64 }}
          iap-oauth-client-id: ${{ secrets.IAP_OAUTH_CLIENT_ID }}
          service-account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: get output
        run: echo '${{ steps.iap-token.outputs.token }}'

  json:
    name: with json creds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: iap-token
        name: get IAP token
        uses: ./get-iap-token
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          iap-oauth-client-id: ${{ secrets.IAP_OAUTH_CLIENT_ID }}
          service-account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - name: get output
        run: echo '${{ steps.iap-token.outputs.token }}'
